// 4P3X Verse™ — Single Source of Product Truth
// Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™
// DO NOT duplicate product data elsewhere. Edit only here.

window.FOURP3X_PRODUCTS = [
  {
    id: "base-core",
    slug: "base-core",
    name: "4P3X Base Core",
    badge: "Base architecture",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://basev0.vercel.app/",
    screenshot: "screenshots/base-core.png",
    sector: "Reusable Modular Software Base",
    shortDescription: "The reusable foundation behind the entire 4P3X Verse™ — one refactorable base that becomes many products.",
    summary: "The core refactorable foundation behind the 4P3X Verse™: dashboard-first, PWA-ready, demo/live aware, and designed to become many sector products.",
    users: "Founders, product teams, employers, funders, agencies, and organisations looking for adaptable software architecture.",
    proof: "Shows the reusable base system before sector-specific transformation.",
    liveReady: "Demo Mode shows the product. Live Mode runs the product once connected to Supabase, Firebase, or another backend.",
    tags: ["Reusable base", "PWA-ready", "Demo/live", "Dashboard"],
    what: "The 4P3X Base Core is the reusable software architecture that powers the entire 4P3X Verse™ ecosystem. It is the foundation refactored into every other product — a shared dashboard and PWA shell, modular config system, data model patterns, AI guidance zones, demo/live mode switching, and backend-ready planning structure.",
    where: "Applicable across any sector that needs a dashboard, user-facing PWA, admin control panel, or AI-assisted workflow system. Healthcare, logistics, education, wellbeing, compliance, careers, and beyond.",
    why: "Built to prove that one well-designed software base can become many different products through controlled refactoring — avoiding starting from zero each time and enabling rapid, safe product development.",
    when: "When an organisation, product team, or individual needs to prototype, demonstrate, or launch a structured digital product quickly without a full custom build from scratch.",
    who: "Founders, employers, investors, product teams, funders, and technical partners who want to see the architecture behind the 4P3X Verse™ before exploring specific sector products.",
    how: "The base provides a shared PWA shell, configurable data model, admin/user split, demo mode with sample data, AI guidance integration points, and a deployment pathway to connect any backend provider.",
    keyFeatures: ["Dashboard/PWA dual-mode shell","Modular config system","Demo/live mode switching","4 embedded AI assistant zones","Backend-ready data model","Installable PWA structure"],
    architecture: "This is Layer 1 of the 4P3X three-layer model. It sits beneath every product and provides the shared structure that controlled refactoring uses to transform into sector-specific solutions.",
    demoLivePathway: "Demo Mode runs with sample data and no backend required. Live Mode activates by connecting Supabase, Firebase, REST, or another backend, enabling real users, persistent records, sync, and organisation-specific configuration.",
    futurePotential: "Can become any product in the 4P3X Verse™ — or a new sector variant not yet built. The architecture is designed to fork safely into unlimited directions.",
    relevance: "For investors and employers: this base demonstrates the creator's ability to design reusable, scalable software architecture rather than one-off solutions. It is the foundation of every product in this portfolio."
  },
  {
    id: "therapylink",
    slug: "therapylink",
    name: "TherapyLink™",
    badge: "Care pathway demo",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://therapylinkos.vercel.app/4p3x_carelink/ap3x/demo/index.html",
    screenshot: "screenshots/therapylink.png",
    sector: "Therapy, care coordination, patient support",
    shortDescription: "A therapy support and patient pathway product showing how the base becomes a care-focused dashboard and patient PWA.",
    summary: "A therapy support and patient pathway product demonstrating how the base can become a care-focused dashboard and patient PWA experience.",
    users: "Therapists, wellbeing teams, private clinics, support organisations, and care pathway coordinators.",
    proof: "Shows patient PWA logic, dashboard coordination, lesson/content delivery, and backend-ready patient tracking structure.",
    liveReady: "With demo mode off and backend connected, it can support unique patient IDs, persistence, dashboard sync, and real patient workflows.",
    tags: ["Care", "Patient PWA", "Dashboard", "Sync"],
    what: "TherapyLink™ is a working demonstration of how the 4P3X base architecture can support therapy coordination, patient pathway management, wellbeing tracking, and AI-assisted clinical support workflows. It features a therapist dashboard and a patient-facing PWA.",
    where: "Private therapy practices, wellbeing teams, mental health organisations, outpatient services, digital health platforms, and care pathway coordinators.",
    why: "Built to demonstrate that the same modular base can support sensitive, structured, user-centred experiences — not just task management or training. Care pathways, check-ins, and progress visibility are all expressible through the same architecture.",
    when: "When a care organisation needs to manage multiple clients, track pathway progress, monitor risk flags, and deliver guided content at scale — without the cost of a full custom clinical system.",
    who: "Therapists, private practitioners, wellbeing coaches, NHS-adjacent support teams, care pathway coordinators, and digital health product teams.",
    how: "The product features a therapist monitoring dashboard for managing client progress, session notes, flag management, and content delivery — plus a patient PWA for guided recovery, check-ins, and secure communication.",
    keyFeatures: ["Therapist dashboard","Patient PWA","Check-in system","Recovery pathway content","Risk flag management","Local-first privacy-centred design"],
    architecture: "Built from the 4P3X base using the same dashboard/PWA split, configurable data model, and AI guidance zones — refactored with care-sector identity, privacy-first logic, and patient-facing UX.",
    demoLivePathway: "Demo Mode shows all features with anonymised demonstration data. Live Mode connects real patient records, authentication, clinical data handling, and secure backend storage. Does not replace clinical judgement or emergency services.",
    futurePotential: "Could become a full clinical coordination platform with EHR integration, video session support, referral pathways, outcome reporting, and NHS-adjacent compliance.",
    relevance: "Demonstrates the creator's ability to adapt the base architecture into sensitive, regulated sectors while maintaining safety-aware design and clinical boundary awareness."
  },
  {
    id: "autoskill",
    slug: "autoskill",
    name: "AutoSkill OS™",
    badge: "Training platform",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://autoskillos.vercel.app/ap3x/demo/index.html",
    screenshot: "screenshots/autoskill.png",
    sector: "Employee training, onboarding, workplace learning",
    shortDescription: "A modular training and motivation system showing the base as an employee learning and progress platform.",
    summary: "A modular training and motivation system showing how the same base can become an employee learning and progress platform.",
    users: "SMEs, HR teams, factories, training providers, onboarding teams, and internal operations managers.",
    proof: "Demonstrates lessons, employee PWA flow, progress tracking, revisit logic, completion journey, and brandable training structure.",
    liveReady: "Live mode can connect authentication, employee records, course progress, and admin reporting through a backend.",
    tags: ["Training", "Employee PWA", "Progress", "Onboarding"],
    what: "AutoSkill OS™ demonstrates how the 4P3X base architecture can power a complete employee training, onboarding, and skills development platform — with a control dashboard for supervisors and a learning PWA for employees.",
    where: "Manufacturing, logistics, retail, healthcare support, professional services, construction, public sector, and any organisation needing scalable staff training.",
    why: "Built to show that the same base that powers a therapy product can also power a workforce learning system — proving the architecture's adaptability across sectors with completely different user needs and data models.",
    when: "When an organisation needs to onboard new staff quickly, track skills progression, deliver compliance training, or replace paper-based training records with a structured digital system.",
    who: "HR managers, training coordinators, operations supervisors, L&D teams, factory floor managers, and franchise operators needing consistent training delivery.",
    how: "Features a Training Control Dashboard for managers to track progress, flag support needs, manage content, and review completion — plus an Employee Learning PWA for guided modules, competency sign-offs, and personal progress tracking.",
    keyFeatures: ["Training control dashboard","Employee learning PWA","Progress tracking","Competency pathway logic","Supervisor flag system","Offline-capable local-first design"],
    architecture: "Refactored from the 4P3X base with training-sector identity, employee/supervisor split, progress data model, and configurable module delivery.",
    demoLivePathway: "Demo Mode runs all training flows with sample employees and modules. Live Mode connects real employee records, HR systems, course authoring tools, and progress reporting backends.",
    futurePotential: "Could expand to include video lesson delivery, external LMS integration, certification management, franchise training consistency, and AI-powered competency assessment.",
    relevance: "Shows the creator's ability to target B2B workforce markets with a scalable, brandable product built on a reusable architecture — a commercially relevant sector with clear buyer personas."
  },
  {
    id: "bigvs-fleet",
    slug: "bigvs-fleet",
    name: "Big V's Best Routes™ / Fleet OS",
    badge: "Safety-critical navigation",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://bigvsfleetos.vercel.app/",
    screenshot: "screenshots/bigvs-fleet.png",
    sector: "Fleet routing, vehicle safety, legal route planning",
    shortDescription: "A safety and compliance-first navigation concept for vehicle-aware routing, risk flags, and fleet workflows.",
    summary: "A safety and legal compliance-first navigation concept for vehicle-aware routing, route suitability, risk flags, and fleet/driver workflows.",
    users: "Fleet operators, transport firms, delivery businesses, councils, logistics teams, and specialist vehicle operators.",
    proof: "Shows dashboard/PWA route assignment, vehicle profile logic, map layer planning, compliance AI concepts, and safety reporting workflows.",
    liveReady: "Live mode can connect GraphHopper, OSM/MapLibre, Supabase, vehicle data, driver apps, and real-time route/session sync.",
    tags: ["Fleet", "Routing", "Safety", "Compliance AI"],
    what: "Big V's Best Routes™ Fleet OS is a safety-first fleet routing and vehicle-aware navigation platform — designed to help fleet operators plan safer routes, reduce avoidable incidents, manage vehicle suitability, and support driver compliance awareness through an advisory AI layer.",
    where: "Transport companies, logistics operators, council fleet departments, specialist vehicle operators (HGVs, mobile cranes, abnormal loads), delivery networks, and emergency response vehicle fleets.",
    why: "Bridge strikes, weight limit violations, and route compliance failures cost the UK industry hundreds of millions annually. This product demonstrates how technology can support better route planning decisions — even without real-time infrastructure data.",
    when: "When fleet managers need to assign routes to specific vehicle types, track driver progress, flag compliance risks, and manage fleet operations from a single dashboard.",
    who: "Fleet managers, transport controllers, logistics coordinators, compliance officers, and drivers needing route guidance.",
    how: "Features a Fleet Dashboard for route assignment, vehicle profile management, driver oversight, and compliance reporting — plus a Driver PWA for turn-by-turn guidance, check-ins, and evidence capture, and a Controller PWA for supervisory oversight.",
    keyFeatures: ["Fleet command dashboard","Driver PWA","Controller PWA","Vehicle profile logic","Advisory AI compliance layer","Route risk flagging"],
    architecture: "Refactored from the 4P3X base with fleet-sector identity, vehicle/driver/controller three-way split, route data model, and map layer integration points.",
    demoLivePathway: "Demo Mode shows all fleet workflows with sample routes and vehicle profiles. Live Mode integrates with real mapping APIs (GraphHopper, OSM/MapLibre), vehicle databases, and live driver tracking. This is an advisory platform only — does not guarantee legal compliance. Drivers and operators remain responsible for all safety, legal, and operational decisions.",
    futurePotential: "Could integrate with national bridge and weight restriction databases, live traffic data, telematics systems, and fleet management platforms like Samsara or Verizon Connect.",
    relevance: "A commercially significant product demonstrating the creator's ability to tackle safety-critical, compliance-aware markets — with real-world commercial potential in a multi-billion pound sector."
  },
  {
    id: "responselink",
    slug: "responselink",
    name: "ResponseLink OS™",
    badge: "Community response",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://responselinkosv1.vercel.app/",
    screenshot: "screenshots/responselink.png",
    sector: "Welfare visits, outreach, mobile response",
    shortDescription: "A welfare and community response coordination platform with command dashboard, responder PWA, and service user PWA.",
    summary: "A safety-first welfare and community response coordination platform with command dashboard, responder PWA, and service user PWA.",
    users: "Charities, councils, housing teams, outreach groups, volunteer teams, and community support organisations.",
    proof: "Demonstrates mission coordination, responder status, service user check-ins, incident reporting, evidence capture, and advisory AI oversight.",
    liveReady: "With demo mode off and backend configured, it can support real missions, persistent records, authentication, sync, and supervisor review.",
    tags: ["Welfare", "Responder PWA", "Service user", "Evidence"],
    what: "ResponseLink OS™ is an AI-assisted community welfare coordination platform — designed to help organisations coordinate welfare visits, outreach operations, responder workflows, and service user check-ins from a centralised command dashboard.",
    where: "Charities, housing associations, outreach teams, councils, community health organisations, volunteer networks, and public-benefit operations that coordinate field workers.",
    why: "Many welfare organisations still coordinate field operations via WhatsApp groups, paper forms, and phone calls. ResponseLink OS™ demonstrates how a structured, AI-assisted platform can replace fragmented coordination and capture evidence safely.",
    when: "When a welfare team needs to dispatch responders, track missions, capture incident evidence, manage service user check-ins, and escalate risks — all in real time from a single dashboard.",
    who: "Welfare coordinators, community outreach managers, housing support teams, volunteer supervisors, safeguarding officers, and frontline responders.",
    how: "Features a Command Dashboard for mission assignment and oversight, a Responder PWA for field check-ins and evidence capture, and a Service User PWA for welfare check-ins and support requests.",
    keyFeatures: ["Command coordination dashboard","Responder mobile PWA","Service user check-in PWA","Incident reporting","Evidence capture","Advisory AI oversight layer"],
    architecture: "Refactored from the 4P3X base with three-party split (command/responder/service user), welfare-sector data model, evidence capture logic, and escalation workflows.",
    demoLivePathway: "Demo Mode shows all coordination workflows with sample missions and responders. Live Mode connects real authentication, persistent mission records, sync, and supervisor review. This is advisory software only — it does not replace emergency services, safeguarding professionals, clinical judgement, or legal duties. If someone is in immediate danger, contact emergency services.",
    futurePotential: "Could expand to include GPS tracking, real-time mapping, safeguarding referral pathways, council reporting exports, and integration with existing case management systems.",
    relevance: "Demonstrates the creator's ability to handle sensitive, safety-critical community welfare markets with appropriate disclaimer design, safeguarding awareness, and evidence-capture thinking."
  },
  {
    id: "careerlink",
    slug: "careerlink",
    name: "CareerLink OS™",
    badge: "Career support",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://4p3xaiclos.vercel.app/",
    screenshot: "screenshots/careerlink.png",
    sector: "Careers, employment support, progression tracking",
    shortDescription: "A career guidance and support operating system showing the base as a user journey, progress, and support dashboard.",
    summary: "A career guidance and support operating system showing how the base can become a user journey, progress, and support dashboard.",
    users: "Career coaches, training providers, employability programmes, education providers, and job support organisations.",
    proof: "Shows modular guidance flows, dashboard logic, support pathway structure, and user-facing progression experiences.",
    liveReady: "Backend connection can enable real user accounts, case records, support notes, progress evidence, and reporting.",
    tags: ["Career", "Progress", "Guidance", "Support"],
    what: "CareerLink OS™ demonstrates how the 4P3X architecture can power an employment support and career development platform — combining a coach/caseworker dashboard with a jobseeker activity PWA, AI-assisted guidance, and compliance tracking.",
    where: "Employment support programmes, government-funded employability schemes, private career coaching practices, education providers, and job centres.",
    why: "Employment support organisations often lack structured digital tools to track jobseeker progress, evidence weekly hours, flag support risks, and report outcomes to funders. CareerLink OS™ demonstrates a structured solution.",
    when: "When employment coaches need to track client job-search activity, manage caseloads, evidence compliance, flag at-risk clients, and generate outcome reports for funders.",
    who: "Employment coaches, caseworkers, careers advisers, HR support teams, DWP-adjacent programme providers, and job-readiness support organisations.",
    how: "Features a Coach Dashboard for caseload management, progress tracking, and outcome reporting — plus a Jobseeker Activity PWA for logging applications, evidencing hours, completing tasks, and receiving AI-assisted career guidance.",
    keyFeatures: ["Coach/caseworker dashboard","Jobseeker activity PWA","Job-search evidence tracking","Weekly hours compliance","AI career guidance","Caseload management"],
    architecture: "Refactored from the 4P3X base with employability-sector data model, coach/jobseeker split, compliance tracking logic, and AI guidance configuration.",
    demoLivePathway: "Demo Mode runs with sample jobseekers and caseload data. Live Mode connects real user accounts, persistent case records, funder reporting exports, and compliance evidence systems.",
    futurePotential: "Could expand to include Universal Credit compliance modules, DWP reporting integrations, CV builder tools, employer connection pathways, and outcome payment tracking.",
    relevance: "Shows commercial awareness of the publicly funded employment support sector — a multi-billion pound market with clear digital transformation needs and measurable ROI for funders."
  },
  {
    id: "recharge-burnout",
    slug: "recharge-burnout",
    name: "Burnout Recovery OS™",
    badge: "Live Deployed Product",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://burnoutrecoveryos.vercel.app/",
    screenshot: "screenshots/recharge-burnout.png",
    sector: "Burnout recovery, wellbeing, self-guided support",
    shortDescription: "AI-assisted burnout recovery, wellbeing support, reflection, routine-building, and guided self-management platform built as part of the 4P3X Verse™ modular product ecosystem.",
    summary: "Burnout Recovery OS™ shows how the 4P3X Verse™ architecture can be refactored into a wellbeing and recovery support product. It can support guided check-ins, recovery planning, routines, reflection, progress tracking, AI-assisted explanations, and future backend-connected live user workflows. It demonstrates the wider 4P3X principle: one base architecture can become many real sector-ready products.",
    users: "Individuals, wellbeing teams, coaches, employers, and support providers.",
    proof: "Demonstrates how the 4P3X modular architecture adapts into a wellbeing-sector product with guided recovery flows, check-in systems, AI-assisted support, and demo-to-live readiness.",
    liveReady: "With demo mode switched off and a backend such as Supabase, Firebase, or another suitable system connected, Burnout Recovery OS™ can become a live operational wellbeing product with real users, persistent records, progress tracking, secure user data, dashboards, and personalised support workflows.",
    tags: ["Wellbeing", "Burnout Recovery", "AI-Assisted", "Demo to Live"],
    what: "Burnout Recovery OS™ is a live deployed AI-assisted recovery and wellbeing support product built within the 4P3X Verse™ ecosystem. It demonstrates how the same modular 4P3X architecture can be adapted into a focused mental wellbeing, burnout support, guided recovery, reflection, routine-building, and self-management platform. Demo Mode shows the product. Live Mode runs the product.",
    where: "Corporate wellbeing programmes, employee assistance services, personal wellbeing coaching, mental health-adjacent support organisations, and self-guided individual use.",
    why: "Burnout is a significant and growing problem across industries. This product demonstrates how the 4P3X architecture can support sensitive, personalised, self-led wellbeing journeys — not just business workflows.",
    when: "When someone is experiencing burnout, chronic stress, or needs structured support to rebuild energy, focus, and routine — and wants a private, guided wellbeing platform rather than a clinical service.",
    who: "Individuals recovering from burnout, employers providing wellbeing benefits, wellbeing coaches, occupational health teams, and corporate wellness programme providers.",
    how: "Features daily recovery plans, structured programmes, restoration check-ins, AI Guide support, progress tracking, and an energy system — all within the 4P3X Verse™ architecture. Backend connection enables live persistent data, real user accounts, and operational deployment.",
    keyFeatures: ["Daily recovery companion","Structured burnout programmes","Check-in system","AI-assisted guidance","Progress and energy tracking","Demo-to-live pathway"],
    architecture: "Refactored from the 4P3X base with wellbeing-sector UX, guided recovery flows, local-first data model, and daily plan logic. Backend-ready for Supabase or Firebase live deployment.",
    demoLivePathway: "Demo Mode shows the product. Live Mode runs the product. With backend connected: real users, persistent records, progress dashboards, secure data, and personalised support workflows. This is not a medical or crisis service — if someone is in mental health crisis, they should contact their GP, a mental health line, or emergency services.",
    futurePotential: "Could expand to include employer-connected reporting, coach oversight, content library management, personalised AI recovery plans, and integration with occupational health platforms.",
    relevance: "Demonstrates empathy-led design, sensitive UX thinking, and the ability to build wellbeing products that respect user privacy and mental health boundaries. Part of the wider 4P3X Verse™: one reusable modular architecture refactored into multiple sector-ready deployed products."
  },
  {
    id: "fourpaws",
    slug: "fourpaws",
    name: "Four Paws Training & Enrichment Academy™",
    badge: "Pet training LMS",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://fourpawsdemo.vercel.app/ap3x/demo/index.html#deploy",
    screenshot: "screenshots/fourpaws.png",
    sector: "Pet training, education, course delivery",
    shortDescription: "A local-first LMS for puppy training showing course, lesson, quiz, certificate, and dashboard logic.",
    summary: "A local-first learning management system for puppy training and enrichment, showing course, lesson, quiz, certificate, and dashboard logic.",
    users: "Dog trainers, pet education brands, behaviour coaches, and local training businesses.",
    proof: "Demonstrates LMS refactoring, quiz-gated progression, certificates, paid-access concepts, and course content structure.",
    liveReady: "Backend connection can enable real customers, payments, course progress, certificates, admin content, and live enrolment.",
    tags: ["LMS", "Courses", "Certificates", "Pet training"],
    what: "Four Paws Training & Enrichment Academy™ is a working demonstration of how the 4P3X base architecture can power a full learning management system — adapted for the pet training and canine behaviour education sector, with course delivery, lesson progression, quizzes, certificates, and a trainer command centre.",
    where: "Dog trainers, canine behaviour coaches, pet education brands, puppy classes, online training academies, and enrichment businesses looking to deliver structured digital courses.",
    why: "Many pet training businesses deliver value through knowledge and programmes but lack the digital tools to scale — no structured LMS, no certificate system, no AI-assisted client coaching. This demonstrates the gap and the solution.",
    when: "When a trainer wants to move clients from in-person-only to a blended or fully digital learning experience — with structured courses, progress tracking, and automated certificate delivery.",
    who: "Dog trainers, canine behaviour specialists, enrichment coaches, pet business owners, and online training course creators.",
    how: "Features a Trainer Intelligence OS for managing clients, deploying AI coaching assistants, tracking progress, and administering courses — plus a client-facing PWA for course content, lesson completion, quiz-gated progression, and certificate download.",
    keyFeatures: ["Trainer command centre","AI client coaching deployment","Course and lesson delivery","Quiz-gated progression","Certificate system","Client PWA"],
    architecture: "Refactored from the 4P3X base with education-sector LMS logic, trainer/client split, quiz and certificate data model, and AI coaching integration points.",
    demoLivePathway: "Demo Mode shows the full LMS experience with sample courses and client data. Live Mode connects real customer accounts, payment gateways, content management, certificate issuing, and trainer dashboards.",
    futurePotential: "Could expand to include video lesson delivery, live virtual classes, NFC/QR client onboarding, franchise trainer networks, and marketplace distribution for training content.",
    relevance: "Demonstrates the creator's range — from enterprise fleet management to consumer pet education — proving the architecture can serve radically different markets with the same underlying codebase."
  },
  {
    id: "quantum-compliance",
    slug: "quantum-compliance",
    name: "Quantum Compliance OS™",
    badge: "Cyber readiness",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://4p3xaiqc.netlify.app/",
    screenshot: "screenshots/quantum-compliance.png",
    sector: "Quantum-readiness, cyber compliance, SME risk",
    shortDescription: "A defensive quantum-readiness and compliance dashboard for understanding future cryptographic risk and evidence gaps.",
    summary: "A defensive quantum-readiness and compliance dashboard for helping organisations understand future cryptographic risk and evidence gaps.",
    users: "SMEs, consultants, compliance teams, security reviewers, and organisations preparing for future cryptographic transition.",
    proof: "Shows scoring, evidence packs, readiness reporting, consultant dashboard thinking, and backend-ready provider configuration.",
    liveReady: "Live mode can connect secure evidence storage, client records, audit logs, reporting exports, and real compliance workflows.",
    tags: ["Cyber", "Compliance", "Evidence", "Readiness"],
    what: "Quantum Compliance OS™ is a defensive cyber-readiness platform that helps organisations understand where their systems, suppliers, encryption, data handling, and compliance evidence may be exposed to future quantum-era cyber risk — and what steps to take now.",
    where: "SMEs, enterprise IT departments, compliance consultancies, insurance providers, public sector organisations, and any business handling sensitive encrypted data.",
    why: "Post-quantum cryptographic migration is a growing regulatory and commercial concern. Most SMEs have no structured way to assess their exposure, capture evidence, or demonstrate readiness to clients, insurers, or boards.",
    when: "When an organisation needs to assess its quantum-readiness posture, evidence its compliance planning, prepare for future regulatory requirements, or advise clients on post-quantum cryptographic risk.",
    who: "CISOs, IT compliance managers, cyber consultants, risk advisers, board-level decision makers, and SME owners who need to understand their cryptographic risk profile.",
    how: "Features a compliance dashboard with readiness scoring, evidence pack management, portfolio assessment workflows, a PWA for mobile compliance checks, and an AI advisory layer for guided readiness planning.",
    keyFeatures: ["Readiness scoring dashboard","Evidence pack management","Portfolio assessment","Advisory AI guidance","PWA compliance checks","Board-ready reporting"],
    architecture: "Refactored from the 4P3X base with compliance-sector data model, scoring logic, evidence capture system, and advisory AI configuration. Purely defensive and compliance-focused.",
    demoLivePathway: "Demo Mode shows the full compliance workflow with sample organisation data and evidence packs. Live Mode connects real client records, secure evidence storage, audit logs, and reporting exports.",
    futurePotential: "Could expand to include regulatory change monitoring, insurance integration, supplier assessment modules, and automated compliance report generation for NCSC/ISO alignment.",
    relevance: "Demonstrates forward-thinking product development in an emerging compliance market — showing the creator's ability to tackle technically complex, high-value sectors with a structured, advisory-focused approach."
  },
  {
    id: "trustshield",
    slug: "trustshield",
    name: "TrustShield OS™",
    badge: "Reputation monitoring",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://4p3xaitsos.netlify.app/#/welcome",
    screenshot: "screenshots/trustshield.png",
    sector: "Reputation crisis, monitoring, response coordination",
    shortDescription: "A reputation and crisis-response dashboard for monitoring risk signals, coordinating responses, and updating field teams.",
    summary: "A reputation and crisis-response dashboard/PWA concept for monitoring risk signals, coordinating responses, and updating field teams.",
    users: "Companies, public figures, agencies, comms teams, brand managers, and reputation-risk operators.",
    proof: "Shows control dashboard, crisis signal workflows, PWA updates, configuration panels, and advisory AI response concepts.",
    liveReady: "Live mode can connect monitoring APIs, alerting, team workflows, response logs, and configured organisation profiles.",
    tags: ["Reputation", "Crisis", "Monitoring", "PWA alerts"],
    what: "TrustShield OS™ is an always-on reputation and crisis management platform — designed to help organisations monitor configured risk signals, assess emerging threats, coordinate response actions, and update field teams before reputation damage becomes uncontrollable.",
    where: "Corporate communications teams, PR agencies, public figures, brand management consultancies, legal firms, and any organisation where reputation is a critical business asset.",
    why: "Reputation crises can emerge from social media, news coverage, review sites, or coordinated attacks within hours. TrustShield OS™ demonstrates a structured command approach to crisis-aware organisation management.",
    when: "When an organisation needs to monitor configured people, brands, or topics for emerging risk signals — and coordinate an organised response before a situation escalates.",
    who: "Communications directors, PR managers, risk officers, brand managers, legal teams, and corporate affairs professionals.",
    how: "Features a reputation command dashboard for monitoring configured signals, assessing crisis risk levels, managing response workflows, and coordinating team actions — plus a mobile Response PWA for field team updates and evidence capture.",
    keyFeatures: ["Reputation command dashboard","Crisis signal monitoring","Response coordination workflows","Mobile response PWA","Advisory AI assessment","Evidence and timeline capture"],
    architecture: "Refactored from the 4P3X base with reputation-sector data model, risk scoring logic, crisis escalation workflows, and monitoring integration points.",
    demoLivePathway: "Demo Mode shows the full monitoring and response workflow with sample organisation and signal data. Live Mode connects real monitoring APIs, alerting systems, team communication tools, and persistent case records.",
    futurePotential: "Could expand to include real-time social listening, media monitoring API integrations, legal coordination modules, and AI-drafted response suggestions.",
    relevance: "Demonstrates commercial awareness of high-value professional services markets — PR, corporate affairs, and reputation management — where structured digital tools can command significant value."
  },
  {
    id: "kyzel-clarity",
    slug: "kyzel-clarity",
    name: "Kyzel Clarity AI™",
    badge: "AI explanation agent",
    brandLine: "Powered by 4P3X Intelligent AI™ Created by Kyzel Kreates™",
    url: "https://kyzelclarityai.vercel.app/",
    screenshot: "screenshots/kyzel-clarity.png",
    sector: "AI explanation, portfolio communication, technical translation",
    shortDescription: "A specialist AI explanation agent built to translate complex thinking into clear language for any audience.",
    summary: "A specialist AI explanation agent built to translate complex thinking, technical systems, and portfolio work into clear language for any audience.",
    users: "Employers, investors, funders, partners, clients, and non-technical viewers wanting to understand the 4P3X Verse™ and its creator.",
    proof: "Shows four-layer local AI reasoning, voice intelligence, PDF report generation, human explanation modes, and portfolio-native Q&A.",
    liveReady: "Fully functional as a deployed PWA — no backend required. Runs entirely local with embedded reasoning, no cloud API dependency.",
    tags: ["AI agent", "Explanation", "Portfolio", "Local-first"],
    what: "Kyzel Clarity AI™ is a specialist explanation agent built to help translate complex thinking, technical architecture, product systems, and portfolio work into clear, accessible language — for employers, investors, funders, and non-technical viewers. It is not built on the same base architecture as the other 4P3X Verse™ products, but serves as the portfolio's explanation and communication layer.",
    where: "Portfolio reviews, investor pitches, employer interviews, client presentations, funding applications, and any situation where the creator needs to communicate complex work clearly.",
    why: "Technical portfolio work is often impressive but hard to communicate to non-technical audiences. Kyzel Clarity AI™ solves this by acting as an always-available explanation agent that can translate system thinking into plain language.",
    when: "When an investor, employer, or funder needs to understand what the 4P3X Verse™ is, why it matters, what skills it proves, and how it applies to their context — without needing to read technical documentation.",
    who: "Investors, employers, HR decision-makers, funders, grant assessors, clients, and anyone encountering the 4P3X Verse™ for the first time.",
    how: "Features four embedded reasoning layers: intent and audience detection, human-like explanation with tone control, voice intelligence for natural speech interaction, and a downloadable PDF report generator — all running locally with no cloud API.",
    keyFeatures: ["Portfolio-native Q&A engine","Human explanation modes","Voice intelligence","Downloadable PDF reports","4P3X Verse™ explanation","Offline-first PWA"],
    architecture: "Built as a standalone PWA with four local reasoning layers. Not from the 4P3X modular base — designed as a companion explanation tool to support the portfolio, not a sector product refactoring.",
    demoLivePathway: "Fully live and functional as deployed. No demo/live separation required — all features are active in the deployed version with no backend dependency.",
    futurePotential: "Could evolve into a full AI portfolio companion for any technical creator — an always-on explanation agent embedded in any portfolio site.",
    relevance: "Demonstrates the creator's communication intelligence as well as technical skills — showing the ability to explain complex work clearly to any audience, a critical skill for any senior technical, product, or leadership role."
  }
];
